### ISSUE TITLE
Wizualizacja - zbędne opcje

### ISSUE THREAD

**Issue by ggruszczynski** [orgSailingVLM/pySailingVLM#21]
Nie ma potrzeby wizualizacji  - spowalnia program.
Proszę zakomentować tą funkcjonalność.

- [x] red vectors: Apparent + induceed wind
- [x] duplicates of blue and green vectors

![image](https://github.com/zuza3012/sailingVLM/assets/6128943/d130bcfc-98ec-4cba-aa22-250172254671)

**Comment by zuza3012** [comment]
Blue, red and green vectors are now plotted only for first spanwise section on each sail. Red vectors can be turned off by specifying show_induced_wind parameter in function display_winds.
