### ISSUE TITLE
Jupyter notebook example - badge

### ISSUE THREAD

**Issue by ggruszczynski** [orgSailingVLM/pySailingVLM#22]
the launch badge is missing (in the example.ipynb and on the repo landing page - [README.md](https://github.com/zuza3012/sailingVLM/blob/main/README.md)

![image](https://github.com/zuza3012/sailingVLM/assets/6128943/4d8cdd28-9ece-4dbd-b23e-3cfeb93ff35c)

**Comment by zuza3012** [comment]
mybinder.org implemeted
